# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "phusion/ubuntu-14.04-amd64"

  config.vm.define "ce3", primary: true do |ce|
    ce.vm.hostname = "ce3.gluu.dev"
    ce.vm.network "private_network", ip: "172.50.10.10"
    ce.vm.synced_folder "./volumes", "/vagrant"
    ce.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
  SHELL
end
