# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "phusion/ubuntu-14.04-amd64"

  config.vm.define "discovery", primary: true do |discovery|
    discovery.vm.hostname = "gluu.discovery"
    discovery.vm.synced_folder "./volumes/discovery", "/vagrant"
    discovery.vm.network "private_network", ip: "172.10.10.10"
    discovery.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
    end
  end

  config.vm.define "master", autostart: false do |master|
    master.vm.hostname = "gluu-master"
    master.vm.synced_folder "./volumes/master", "/vagrant"
    master.vm.network "private_network", ip: "172.10.10.11"
    master.vm.provider "virtualbox" do |v|
      v.memory = 3072
      v.cpus = 2
    end
  end

  config.vm.define "worker", autostart: false do |worker|
    worker.vm.hostname = "gluu-worker"
    worker.vm.synced_folder "./volumes/worker", "/vagrant"
    worker.vm.network "private_network", ip: "172.10.10.12"
    worker.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -q
  SHELL
end
