# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "phusion/ubuntu-14.04-amd64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.define "registry", primary: true do |registry|
    registry.vm.hostname = "registry"
    registry.vm.network "private_network", ip: "172.20.20.20"
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' > /etc/apt/sources.list.d/docker.list
    apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    apt-get update -q
    apt-get install -y docker-engine=1.8.3-0~trusty
  SHELL
end
