# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "phusion/ubuntu-14.04-amd64"

  config.vm.define "discovery", primary: true do |discovery|
    discovery.vm.hostname = "gluu.discovery"
    discovery.vm.synced_folder "./volumes/discovery", "/vagrant"
    discovery.vm.network "private_network", ip: "172.20.20.20"
    discovery.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -q
    apt-get install -y apt-transport-https ca-certificates
    echo 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' > /etc/apt/sources.list.d/docker.list
    apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    apt-get update -q
    apt-get install -y docker-engine
  SHELL
end
