# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "phusion/ubuntu-14.04-amd64"

  config.vm.define "master", primary: true do |master|
    master.vm.hostname = "redis-master"
    master.vm.network "private_network", ip: "172.20.20.10"
    master.vm.synced_folder "./volumes/master", "/vagrant"

    config.vm.provision "shell", inline: <<-SHELL
      apt-get install -y redis-server
      echo 'include /etc/redis/redis.override.conf' >> /etc/redis/redis.conf
      cp /vagrant/redis.override.conf /etc/redis/redis.override.conf
      service redis-server restart
    SHELL
  end

  config.vm.define "slave", autostart: false do |slave|
    slave.vm.hostname = "redis-slave"
    slave.vm.network "private_network", ip: "172.20.20.11"
    slave.vm.synced_folder "./volumes/slave", "/vagrant"

    config.vm.provision "shell", inline: <<-SHELL
      apt-get install -y redis-server
      echo 'include /etc/redis/redis.override.conf' >> /etc/redis/redis.conf
      cp /vagrant/redis.override.conf /etc/redis/redis.override.conf
      service redis-server restart
    SHELL
  end
end
